## Write a Numpy program to compute the multiplication of two given matrixes

In [13]:
import numpy as np
def mult(mat1,mat2):
    return np.dot(mat1,mat2)

In [16]:
mat1 = np.array([[1,2,3],
                 [4,5,6]])
mat2 = np.array([[7,8],
                 [10,11],
                 [1,2]])
mult(mat1,mat2)

array([[30, 36],
       [84, 99]])

## Write a NumPy program to compute the determinant of a given square array

In [11]:
arr = np.identity(3)
np.linalg.det(arr)

1.0

## Write a NumPy program to compute the cross product of two given vectors

In [17]:
v1 = np.array([11,12,13])
v2 = np.array([1,2,3])
np.cross(v1,v2)

array([ 10, -20,  10])

## Write a NumPy program to compute the condition number of a given matrix

In [18]:
def condition(matx):
  return np.linalg.cond(matx)

In [24]:
matrix = np.arange(1,10).reshape(3,3)
print(matrix)
condition(matrix)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


3.813147060626918e+16

## Write a NumPy program to compute the inverse of a given matrix

In [12]:
def inverse(matx):
  return np.linalg.inv(matx)

In [7]:
mat = np.array([[ 7, 16],
                [40, 55]])
inverse(mat)

array([[-0.21568627,  0.0627451 ],
       [ 0.15686275, -0.02745098]])